/**
 * @86d-app/core
 *
 * Core types and utilities for the 86d module system.
 * This package provides everything module authors need to build modules.
 */

// MobX re-exports moved to @86d-app/core/state (avoids pulling
// mobx-react-lite into server bundles where React hooks are unavailable).
export type { BaseAdapter } from "./adapters";
export {
	type AdminEndpointContext,
	createAdminEndpoint,
	createRouter,
	createStoreEndpoint,
	type Endpoint,
	type EndpointContext,
	type InputContext,
	type Middleware,
	type RouterConfig,
	type StoreEndpointContext,
	type ZodInfer,
	type ZodSchema,
	type ZodType,
	z,
} from "./api";
export {
	type AnyCapabilityDefinition,
	acceptCapability,
	type CapabilityAcceptance,
	type CapabilityDecision,
	type CapabilityDefinition,
	type CapabilityFailure,
	type CapabilityHandler,
	type CapabilityInvoker,
	type CapabilityKernelFailure,
	type CapabilityKernelFailureCode,
	type CapabilityProvider,
	type CapabilityProviderContext,
	type CapabilityRejected,
	type CapabilityRequest,
	type CapabilityResult,
	type CapabilitySuccess,
	defineCapability,
	type ModuleCapabilities,
	provideCapability,
} from "./capabilities";
export type {
	ActionLevel,
	ActorReference,
	Approval,
	AuditEvent,
	AuthoritativePlane,
	AuthoritySnapshot,
	ChangeSet,
	CommandExecutionResponse,
	CommandFailure,
	CommandFailureCode,
	CommandReceipt,
	CommandReference,
	CommandRequest,
	CommandStatus,
	Confirmation,
	GrantUse,
	JsonValue,
	StandingPermission,
	StandingPermissionUseReservation,
	TargetReference,
	Workflow,
	WorkflowAttempt,
	WorkflowState,
	WorkflowStep,
} from "./commands";
export {
	actionLevelSchema,
	actorReferenceSchema,
	approvalSchema,
	auditEventSchema,
	authoritativePlaneSchema,
	authoritySnapshotSchema,
	baseRevisionSchema,
	canTransitionCommand,
	canTransitionWorkflow,
	changeSetProposalSchema,
	changeSetSchema,
	commandExecutionResponseSchema,
	commandFailureCodeSchema,
	commandFailureSchema,
	commandReceiptSchema,
	commandReferenceSchema,
	commandRequestSchema,
	commandStatusSchema,
	confirmationSchema,
	estimatedChargeSchema,
	grantUseSchema,
	jsonValueSchema,
	standingPermissionSchema,
	standingPermissionUseReservationSchema,
	targetReferenceSchema,
	workflowAttemptSchema,
	workflowSchema,
	workflowStateSchema,
	workflowStepSchema,
} from "./commands";
export {
	abandonedCartRecoveryResolveCapability,
	cartSnapshotCapability,
	customerContactResolveCapability,
	customerIdentityResolveCapability,
	discountCodeCapability,
	giftCardCheckoutCapability,
	inventoryCheckoutCapability,
	notificationCreateCapability,
	orderCreateCapability,
	orderCustomerAuthorizeCapability,
	orderLineQuantityValidateCapability,
	orderPurchaseVerifyCapability,
	paymentCheckoutCapability,
	paymentIntentCapability,
	priceListResolveCapability,
	productPriceConversionCapability,
	productResolveCapability,
	shippingQuoteCapability,
	storeCreditCheckoutCapability,
	storePresentationResolveCapability,
	taxQuoteCapability,
	taxQuoteV2Capability,
} from "./commerce-capabilities";
export {
	computeInitOrder,
	formatViolations,
	getRequiredModuleIds,
	normalizeRequires,
	validateContracts,
} from "./contracts";
export {
	type AnyDurableEventConsumer,
	type AnyDurableEventDefinition,
	catalogPublishedV1,
	consumeDurableEvent,
	type DurableEventConsumer,
	type DurableEventConsumerContext,
	type DurableEventDefinition,
	type DurableEventEnvelope,
	type DurableEventInput,
	type DurableEventPayload,
	defineDurableEvent,
	durableEventKey,
	inventoryStockAdjustedV1,
	inventoryStockAdjustedV2,
	type LockingModuleDataTransaction,
	type ModuleDataTransaction,
	type ModuleTransactionRunner,
} from "./durable-events";
export {
	collectEndpointExposures,
	createEndpointExposureResolver,
	ENDPOINT_EXPOSURES,
	type EndpointExposure,
	type EndpointExposureEntry,
	type EndpointExposureOptions,
	type EndpointExposureViolation,
	endpointExposure,
	formatEndpointExposureViolations,
	isEndpointExposure,
} from "./endpoint-exposure";
export {
	formatModuleClientEndpointReferenceConflicts,
	type ModuleClientEndpointReference,
	type ModuleClientEndpointReferenceConflict,
	type ModuleClientEndpointSurface,
	validateModuleClientEndpointReferences,
} from "./endpoint-references";
export {
	createEventBus,
	createScopedEmitter,
	type EventBus,
	type EventBusOptions,
	type EventErrorHandler,
	type EventHandler,
	type ModuleEvent,
	type ScopedEventEmitter,
} from "./events";
export { inventoryCheckoutV2Capability } from "./inventory-reservation-capability";
export {
	formatPathConflicts,
	type ModulePathConflict,
	type ModulePathKind,
	type ModulePathSource,
	validateUniquePaths,
} from "./paths";
export type {
	PaymentConnectionCapability,
	PaymentConnectionMode,
	PaymentConnectionProvider,
	PaymentOperationPayload,
	PaymentProviderOperationOutcome,
	PaymentProviderOperationRequest,
	PaymentProviderReconciliationRequest,
} from "./payment-connection-provider";
export type {
	PaymentProvider,
	ProviderIntentResult,
	ProviderRefundResult,
} from "./payment-provider";
export {
	escapeScriptContent,
	isSafeUrl,
	normalizeWhitespace,
	sanitizeHtml,
	sanitizeText,
	stripTags,
} from "./sanitize";
export type {
	Awaitable,
	LiteralString,
	LiteralUnion,
	Prettify,
	Primitive,
} from "./types/helper";
export type {
	AdminPage,
	ContractViolation,
	HookEndpointContext,
	Module,
	ModuleConfig,
	ModuleContext,
	ModuleController,
	ModuleControllers,
	ModuleDataService,
	ModuleExports,
	ModuleId,
	ModuleOptions,
	ModuleRequires,
	ModuleStatus,
	Session,
} from "./types/module";
export type {
	BaseModelNames,
	FieldAttribute,
	FieldAttributeConfig,
	FieldType,
	ModelNames,
	ModuleSchema,
} from "./types/schema";
