#!/usr/bin/env tsx
/**
 * Generate unified module component documentation.
 *
 * Reads COMPONENTS.md from each module and concatenates into docs/MODULE_COMPONENTS.md.
 * Modules without COMPONENTS.md are listed with placeholder entries.
 *
 * Run: bun run generate:component-docs
 */

import { existsSync, readFileSync, readdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const ROOT = join(import.meta.dirname, "..");
const MODULES_DIR = join(ROOT, "modules");
const OUTPUT = join(ROOT, "docs", "MODULE_COMPONENTS.md");

const MODULES_WITH_STORE_COMPONENTS = [
	"cart",
	"products",
	"newsletter",
	"reviews",
	"orders",
	"discounts",
	"subscriptions",
	"digital-downloads",
	"gift-cards",
	"wishlist",
	"tax",
	"blog",
];

function main() {
	const sections: string[] = [];
	sections.push(`# Module Components Reference

Unified reference for store MDX components provided by 86d modules.
Generated by \`bun run generate:component-docs\`.

`);

	for (const mod of MODULES_WITH_STORE_COMPONENTS) {
		const compPath = join(MODULES_DIR, mod, "COMPONENTS.md");
		if (existsSync(compPath)) {
			const content = readFileSync(compPath, "utf-8");
			sections.push(`## ${mod} (\`@86d-app/${mod}\`)\n\n`);
			sections.push(content);
			sections.push("\n\n---\n\n");
		} else {
			sections.push(`## ${mod} (\`@86d-app/${mod}\`)\n\n`);
			sections.push(
				`*No COMPONENTS.md yet. Add \`modules/${mod}/COMPONENTS.md\` to document store components.*\n\n`,
			);
		}
	}

	sections.push(`
## Adding Component Documentation

Each module with store components should have a \`COMPONENTS.md\` documenting:
- Component name and purpose
- Props (type, default, description)
- Usage example in MDX
`);

	writeFileSync(OUTPUT, sections.join(""));
	console.log(`Wrote ${OUTPUT}`);
}

main();
