name: CI

on:
  pull_request:
    branches: ["*"]
  push:
    branches: ["main"]
  merge_group:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

# You can leverage Vercel Remote Caching with Turbo to speed up your builds
# @link https://turborepo.org/docs/core-concepts/remote-caching#remote-caching-on-vercel-builds
env:
  FORCE_COLOR: 3
  TURBO_TEAM: ${{ vars.TURBO_TEAM }}
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup
        uses: ./internals/github/setup

      - name: Copy env
        shell: bash
        run: cp .env.example .env

      - name: Check
        run: bun check

  typecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup
        uses: ./internals/github/setup

      - name: Generate modules
        run: bun run generate:modules

      - name: Typecheck
        run: bun typecheck

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup
        uses: ./internals/github/setup

      - name: Copy env
        shell: bash
        run: cp .env.example .env

      - name: Unit tests
        run: bun run test

  test-e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup
        uses: ./internals/github/setup

      - name: Generate modules
        run: bun run generate:modules

      - name: Install Playwright
        run: bunx playwright install --with-deps chromium

      - name: Copy env
        shell: bash
        run: cp .env.example .env

      - name: E2E tests
        run: bun test:e2e

      - uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: playwright-report
          path: playwright-report/
